services:
  - type: web
    name: hn-ai-chatbot
    runtime: node
    plan: free
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
